Universe     = vanilla
Executable   = /home/qiqianf2/LC-Agent/sft_rl_training/scripts/run_bench_c23.sh

Log          = /home/qiqianf2/LC-Agent/sft_rl_training/logs/bench_c23_$(Cluster).log
Output       = /home/qiqianf2/LC-Agent/sft_rl_training/logs/bench_c23_$(Cluster).out
Error        = /home/qiqianf2/LC-Agent/sft_rl_training/logs/bench_c23_$(Cluster).err

Requirements = (Machine == "vision-c23.cs.illinois.edu")

request_gpus = 1
request_cpus = 4
request_memory = 32GB

getenv = True

Queue
