Universe     = vanilla
Executable   = /home/qiqianf2/LC-Agent/sft_rl_training/scripts/run_grpo.sh
Log          = /home/qiqianf2/LC-Agent/sft_rl_training/logs/grpo_$(Cluster).log
Output       = /home/qiqianf2/LC-Agent/sft_rl_training/logs/grpo_$(Cluster).out
Error        = /home/qiqianf2/LC-Agent/sft_rl_training/logs/grpo_$(Cluster).err

Requirements = (Machine == "vision-c22.cs.illinois.edu")
request_gpus = 4
request_cpus = 16
request_memory = 128GB

getenv = True

Queue
