Universe     = vanilla
Executable   = /home/qiqianf2/LC-Agent/sft_rl_training/scripts/run_grpo_v2.sh
Log          = /home/qiqianf2/LC-Agent/sft_rl_training/logs/grpo_v2_$(Cluster).log
Output       = /home/qiqianf2/LC-Agent/sft_rl_training/logs/grpo_v2_$(Cluster).out
Error        = /home/qiqianf2/LC-Agent/sft_rl_training/logs/grpo_v2_$(Cluster).err

Requirements = (Machine == "vision-c21.cs.illinois.edu")
request_gpus = 1
request_cpus = 8
request_memory = 48GB

getenv = True

Queue
